/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample.graalvm;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest1 {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getJavalin(), "app should have a javalin instance");
    }
}
